name: cron

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # tag=v3.3.0

      - uses: sigstore/cosign-installer@c85d0e205a72a294fe064f618a87dbac13084086 # v2.8.1

      - name: Docker registry login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Publish
        uses: renovatebot/internal-tools@409dc89a2117bffef282eab5d7cbffdffc4d1d99 # tag=v1.14.12
        with:
          command: docker-builder
          prune: true
